#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: password
POSTGRES_SQL_DB: clients
POSTGRES_SQL_HOST: localhost
#POSTGRES_SQL_HOST: 192.168.1.216
POSTGRES_SQL_PORT: 5432

#Server
#SERVER_PORT: 9000
SERVER_PORT: 8080
ACTIVE_PROFILE: dev
