#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: password
POSTGRES_SQL_DB: clients
POSTGRES_SQL_HOST: localhost
#POSTGRES_SQL_HOST: 192.168.1.216
#POSTGRES_SQL_PORT: 5433
#POSTGRES_SQL_PORT: 192.168.7.97:52329
POSTGRES_SQL_PORT: 5432

#Server
#SERVER_PORT: 9000
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOSTL: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ADDRESS: marcosondruska@gmail.com
EMAIL_PASSWORD: eweq xthr owsm yrmw
#Must be app password for gmail
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
